### ISSUE TITLE
in some cases, the -std=c++11 flag is being ignored

### ISSUE THREAD

**Issue by dagorym** [fermi-lat/healpix#3]
I've been trying to set up an environment to develop and compile the science tools.  However building likelihood fails with the following errors:

/home/tstephen/builds/lib/redhat7-x86_64-64bit-gcc48/libhealpix.so: undefined reference to `fitshandle::open(std::string const&)'

/home/tstephen/builds/lib/redhat7-x86_64-64bit-gcc48/libhealpix.so: undefined reference to `fitshandle::create(std::string const&)'

Those functions are defined in the libcxxsupport.a librar which is included in the list of libraries to be linked by the compile command.  However if you look closely at the symbols, there is a mismatch.  In the libcxxsupport.a library the signature is:
`fitshandle::open(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)`
whereas in the libhealpix.so file it is:
`fitshandle::open(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)`

Checking the build commands the -std=c++11 flag is passed on the command line when compiling the Map.cpp file (where these functions are called) but it is not included in the construction of the libhealpix.so library that includes the object file created when compiling Map.so.  However, I don't think this is the issue as the libBayesianBlocks.so library is built the same way and its reference to the fitshandle::open() function includes the std::__cxx11 identifier in the signature.

The environment this is occurring in is:
- Scientific Linux 7.6 running in a Hyper-V virtual machine on Windows 10
- gcc 4.8.5
- in a conda environment set up following the pattern in the  Fermitools-conda/build.sh file from this repository

**Comment by dagorym** [comment]
Actually, I"m not even sure why the BayesianBlocks library has the function included because I can't seem to see a reason.  As far as I can tell, it doesn't ever use the Healpix library.  So that might be a red herring.

**Comment by jasercion** [comment]
@dagorym Is this still occurring with the latest iteration of the tools?  I believe the changes I made to the patch release should have fixed it.

**Comment by dagorym** [comment]
No, it is building fine now.  Closing the issue.
